### PR TITLE
feat: Add Custom Fetcher Support to SimpleSDK Constructor

### PR DESCRIPTION
**Pull request by mindrunner**
🚀 Description

This PR extends the SimpleSDK class constructor to support custom fetcher functions, allowing it to integrate seamlessly with a variety of HTTP libraries. Importantly, this change is backward-compatible, retaining support for existing axios and fetch configurations.

🤔 Why is this change important?
- **Versatility**: Removes the limitation of only being able to use Axios or Fetch for HTTP requests.
- **Backward Compatibility**: Old configurations with Axios and Fetch will continue to work as before.
- **User-Choice**: Enables the developer to use other HTTP libraries like Superagent.

🛠 Technical Details

- **New Type Added**: FetcherFunction defines the signature of the custom fetcher.
```
type FetcherFunction = <T>(params: any) => Promise<T>;
```

- **Extension in FetcherOptions Type**: New fetcher option added.
```
type FetcherOptions = { axios: AxiosRequirement } | { fetch: typeof fetch } | { fetcher: FetcherFunction };
```

- **Fetcher Construction**: New function constructFetcher() chooses the appropriate fetcher.
```
const constructFetcher = (options: FetcherOptions): FetcherFunction => {
    if ('axios' in options) return constructAxiosFetcher(options.axios);
    if ('fetch' in options) return constructFetchFetcher(options.fetch);
    return options.fetcher;
};
```

**Example Implementation (superagent)**

```
import { FetcherFunction } from '@paraswap/sdk/dist/types'
import superagent from 'superagent'

export const superagentFetcher = (): FetcherFunction =>
  async function <T>(params: any): Promise<T> {
    if (params.method.toLowerCase() === 'post') {
      const response = await superagent.agent.post(
        params.url,
        params.data,
        params.headers
      )

      return response.data
    } else {
      const response = await superagent.agent.get(params.url, params.headers)

      return response.data
    }
  }


const fetcher: FetcherFunction = superagentFetcher();
const sdk = constructSimpleSDK({ fetcher });

```

### CODE REVIEW

**Comment by Velenir** [comment]
Hello @mindrunner ! 

Nice suggestion.
Can you create a `src/examples/customFetcher.ts` with a fully-realized example of using superagent :pray: 
There please make use of `FetcherError` class for a reliable error structure and AbortSignal, also add a `FetcherFunction` reexport from `src/index`.

Btw, it is already possible to use a custom `FetchFunction` directly with `constructPartialSDK`, and for `constructSimpleSDK` you can make a `typeof fetch` function, something like [this](https://www.typescriptlang.org/play?ssl=4&ssc=25&pln=4&pc=30#code/JYWwDg9gTgLgBFApgRwK6IM7wGZQiOAIg1TESgEMBzRAOxkIChRJY4BvAYwlqylU4wAYohicAFiLHjyAGjjdeMfoIDKLADaJVAEQDS8qRPIBRKHigBfOLnxEAAmAqUMAdwpgA9BgAmAayZGRSwbUQkhVFpOAC44GABPMghsUOk4AF44Cgx4qLgACiRkeQgwGGAeDABKDIA+DkY4JrhPTzhI4GxoAnd4uIg4GnhUKA1G5uDh0Yy4WkRXOAAlFHQsQpQqgDoRsea4ToLS8sqAfk2QUXEIHzOYCAAZCFdyAGFsxHya9O+4AHJILC-OAAMmBcCOFV4ZwARtd4jV2OM9k1JghMJBeIgZhR3MB4EVVjBNgCYPkdlsMKJ8hDTpsZBQfOQMAAfZnsSwUug+allSEYTawnzwxgi5HNJAwEa0NEYDGUgVwpFwayIDSUhpi1FIWWVLGZHEUPFotCYIlDMmjTmkmlQumIBlM1nsqqi5ESqUyuWIBVCpWWJWtOAAQR8Pjg5AscHEFFoPg0wFoVDgrjx4jgRhkUDMFgDbWjsa04N5lU2GGAVFoFDGlgA3CKgpV4L4-DNJioYOpwFpdHp8uxUhJYtgwpJIpx5BJDbQAJI+WIARmVVTrQA).

But having an extra option `type FetcherOptions |= { fetcher: FetcherFunction }`, like you suggest, would be best.

**Comment by mindrunner** [comment]
Hi @Velenir,

Thank you for your prompt reply.

> Can you create a `src/examples/customFetcher.ts` with a fully-realized example of using superagent?

Certainly, I can create that example. However, integrating `superagent` would make the SDK and its users dependent on that library. My initial objective was to potentially remove older functionalities, including dependencies on `axios` and `fetch`, in a future major release to streamline the SDK. If your vision differs, I'm open to implementing the superagent example.

Please share your thoughts. I'll proceed with the example in the coming days.

Best regards,
Lukas

**Comment by Velenir** [comment]
> integrating `superagent` would make the SDK and its users dependent on that library. My initial objective was to potentially remove older functionalities, including dependencies

You are right about that.
A `customFetcher` example doesn't need to depend specifically on `superagent`, and of course adding another devDependency isn't ideal. Still, having a more specific example that demonstrates use-case of a 3rd party library is best, I believe.
Your intent for custom fetcher is to be able to use it with a library, any library, capable of http requests, which I'm very much in favor of.
So how about we make an example with something generic but that would still reflect an actual library. [Like this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMYQHYGcZQK5JgMQFMYkALIk0wqAGjhQy1xgGVQwAbQlgEQGk6FMtQCiUKNAC+cAGYSQcAEQABMAEMoa9AHc1YAPToAJgGtFAKHbR4COEKpR82VHmBo40uRAUByVRq1dA2MTfSNgTH0YAE8wQnQfc3N9fTgQCCQTOHRsOM0Ac0JUeHSjbC44bWAYUghseDUjcNR8uDU4I0I41E6XaMti6hk1JEI4FlzqAEFC4pYYNRhgJHM4OEIADxgio3Q4AAV5CMIAHgRVtbgAIwgjaIAuNtRogG4LtYgTR5uILjVUN6XbILGDYdCPVDYEBXaiAy6YRZggDCt0IEKhMKgcLW1AkUEeww46DGAB9EMDEeC4JDobC4NsthtHpgoMAWh44ZIAHyIC7EmAACiojWoVIASoQUFAjCcWWz8nQ5S0uQBKR41CJwwqC7BQDjMrDytX00iai6QTAC3X64GslrGjXoOHEnoCm53R7-aIO01O8ySZKpMBQYg7SpjIwQOAAAyssGykwKRXgXgUihyeTUsxgFk6SA4GjGDEwCcz2ceEzyM2T80Wyze5k2kHjxfgGeoWeT9mocAAvHABcbu45nK53L2uRctNEXLJR0t3AKIGAFxgVbygcAZAPl6v0AA6EDEWpGfcwCAAGQg2moSK0hEHfd7-Z8FpgPjgADJP3AfEZFmoH5snAu5uGuG5AvQaAliG6CQBgYz9moujVKWHbZu8kH7m+S4rmBB7WiqmFAvu-K4XuAD8+7Cp0UB7CSZIIJIRGQZcpE7OR+H7v+Cwqg2rEhqCUCoHAsHwcS+7uq8mHSIQRJjOcrGtqJ8TiYhbQoW2iadsUxFsdqnHQfuhF6Ws7GCqB0FUTRopwAxiDMfxkGCbqIlidBhCSbc0lAgGmEpHAUxNOs4jQHApD-EYHDypU1SkHYxDCFAYh4v5qQRT0FSWRgpHAPkqBqBwFySA2ykyIlDiPMOTguKufZoUmxTDoObzKSE9WtjgeBsOAXC8HwAq2OVlDUHQZBqGyACSRiPAAjB4fHmEAA)

Wdyt?

**Comment by mindrunner** [comment]
Thanks for the example. I added it to the PR! :)

**Comment by Velenir** [comment]
Great.
Just add a couple more changes and I'll be happy to merge this.
1. Reexport `FetcherError` as a value (it is currently [exported as a type only](https://github.com/mindrunner/paraswap-sdk/blob/77110874c66ca14d496533f3c77e8fbaf7f59ce2/src/index.ts#L241)), so that it can be used in error handling in custom fetcher.
2. Reexport[ `FetcherFunction`](https://github.com/mindrunner/paraswap-sdk/blob/77110874c66ca14d496533f3c77e8fbaf7f59ce2/src/types.ts#L42) from[ `src/index` ](https://github.com/mindrunner/paraswap-sdk/blob/77110874c66ca14d496533f3c77e8fbaf7f59ce2/src/index.ts#L194)so it's accessible as a 1st level import to make creating customFetchers easier.

A good indication of whether you have reexported everything necessary is whether you can import all you need from /index:
```ts
//customFetcher.ts
import { constructSimpleSDK, FetcherError, FetcherFunction } from '../';
```

**Comment by mindrunner** [comment]
@Velenir Let me know if you need anything else to get this merged! :)

**Comment by Velenir** [comment]
> @Velenir Let me know if you need anything else to get this merged! :)

Thank you for pinging me.
Nothing else needed, I'll merge and make a new release today.

**Review by Velenir — APPROVED** [review]

**Pull request merged**
